tf:
  _target_: tabdd.config.EncoderTuneConfig
  encoder_name: TFAutoEncoder
  cls:
    _target_: hydra.utils.get_class
    path: tabdd.models.encoder.TFAutoEncoder
  tune_params:
    n_layers:
      _target_: ray.tune.choice
      categories: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    n_heads:
      _target_: ray.tune.choice
      categories: [2, 4, 8, 16]
    d_qkv:
      _target_: ray.tune.choice
      categories: [0, 4, 8, 16, 32, 64, 128]
    layer_norm_eps:
      _target_: ray.tune.choice
      categories: [0.00001, 0.0001, 0.001, 0.01, 0.1]
    mlp_dim:
      _target_: ray.tune.choice
      categories: [128, 256, 512, 1024, 2048]
    decoder_hidden_dims:
      _target_: ray.tune.choice
      categories:
        - [100]
        - [100, 100]
        - [100, 100, 100]
        - [100, 100, 100, 100]
        - [200]
        - [200, 200]
        - [200, 200, 200]
        - [200, 200, 200, 200]
    dropout_p:
      _target_: ray.tune.choice
      categories: [0, 0.1, 0.2, 0.3, 0.4]
    opt_name:
      _target_: ray.tune.choice
      categories: [Adam]
    opt_lr:
      _target_: ray.tune.choice
      categories: [0.1, 0.01, 0.001]
    opt_wd:
      _target_: ray.tune.choice
      categories: [0, 0.001, 0.0001]
    sch_names:
      _target_: ray.tune.choice
      categories:
        - []
        - [ReduceLROnPlateau]
        - [CosineAnnealingLR]



          # n_layers:
          #   _target_: ray.tune.choice
          #   categories: [2]
          # n_heads:
          #   _target_: ray.tune.choice
          #   categories: [4]
          # d_qkv:
          #   _target_: ray.tune.choice
          #   categories: [128]
          # layer_norm_eps:
          #   _target_: ray.tune.choice
          #   categories: [0.0001]
          # mlp_dim:
          #   _target_: ray.tune.choice
          #   categories: [512]
          # decoder_hidden_dims:
          #   _target_: ray.tune.choice
          #   categories:
          #     - [100, 100]
          # dropout_p:
          #   _target_: ray.tune.choice
          #   categories: [0.2]
          # opt_name:
          #   _target_: ray.tune.choice
          #   categories: [Adam]
          # opt_lr:
          #   _target_: ray.tune.choice
          #   categories: [0.01]
          # opt_wd:
          #   _target_: ray.tune.choice
          #   categories: [0.0001]
          # sch_names:
          #   _target_: ray.tune.choice
          #   categories:
          #     - [CosineAnnealingLR]
