gm:
  _target_: tabdd.config.DistillConfig
  distill_method_name: gm
  is_random: true
  is_cluster: false
  is_baseline: false
  can_use_encoder: true
  can_distill: true
  args:
    n_epochs: 500
    mlp_dim: 1024
    lr_mlp: 0.01
    lr_data: 0.1
    mom_data: 0.5
    n_hidden_layers: 2
