kip:
  _target_: tabdd.config.DistillConfig
  distill_method_name: kip
  is_random: true
  is_cluster: false
  is_baseline: false
  can_use_encoder: true
  can_distill: true
  args:
    n_epochs: 1000
    mlp_dim: 1024

