FTTransformer:
  _target_: tabdd.config.ClassifierTuneConfig
  classifier_name: FTTransformer
  default_params:
    device: cpu
    d_block: 128
    n_blocks: 2
    attention_n_heads: 8
    attention_dropout: 0.15
    ffn_d_hidden_multiplier: 1.25
    ffn_dropout: 0.05
    residual_dropout: 0
    opt_name: Adam
    opt_lr: 0.0001
    opt_wd: 0.00001
    early_stopping: True
    max_epochs: 1000000
    patience: 16
  tune_params:
    d_block:
      _target_: ray.tune.choice
      categories: [16, 32, 64, 128, 256]
    n_blocks:
      _target_: ray.tune.choice
      categories: [2,3,4,5]
    attention_n_heads:
      _target_: ray.tune.choice
      categories: [2,3,4]
    attention_dropout:
      _target_: ray.tune.choice
      categories: [0, 0.1, 0.2, 0.3]
    ffn_d_hidden_multiplier:
      _target_: ray.tune.choice
      categories: [1,1.25,1.5,2]
    ffn_dropout:
      _target_: ray.tune.choice
      categories: [0, 0.1, 0.2, 0.3]
    residual_dropout:
      _target_: ray.tune.choice
      categories: [0, 0.1, 0.2, 0.3]
    opt_name:
      _target_: ray.tune.choice
      categories: [Adam]
    opt_lr:
      _target_: ray.tune.choice
      categories: [0.1, 0.01, 0.001]
    opt_wd:
      _target_: ray.tune.choice
      categories: [0.01, 0.001, 0.0001, 0]
    early_stopping:
      _target_: ray.tune.choice
      categories: [True]

  use_sample_weight: false
  use_n_jobs: false
